version: '3.3'

services:

   eureka-server:
     image: codemotiontraining/discovery-eureka-server:latest
     ports:
       - "8761:8761"
     restart: always
     environment:
       PORT: 8761
     network_mode: "host"
      
   product-service-1:
     depends_on:
       - eureka-server
     image: codemotiontraining/discovery-product-service:latest
     ports:
       - "8081:8081"
     restart: always
     environment:
       PORT: 8081
       REGISTRATION_ENDPOINT: "http://eureka-server:8761/eureka/"
     network_mode: "host"
       
   product-service-2:
     depends_on:
       - eureka-server
     image: codemotiontraining/discovery-product-service:latest
     ports:
       - "8082:8082"
     restart: always
     environment:
       PORT: 8082
       REGISTRATION_ENDPOINT: "http://eureka-server:8761/eureka/"  
     network_mode: "host"

   product-service-3:
     depends_on:
       - eureka-server
     image: codemotiontraining/discovery-product-service:latest
     ports:
       - "8083:8083"
     restart: always
     environment:
       PORT: 8083
       REGISTRATION_ENDPOINT: "http://eureka-server:8761/eureka/"
     network_mode: "host"

   shop-service:
     depends_on:
       - eureka-server
     image: codemotiontraining/discovery-shop-service:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       PORT: 8080
       REGISTRATION_ENDPOINT: "http://eureka-server:8761/eureka/"
     network_mode: "host"
