version: '3.3'

services:

   zuul-proxy:
     depends_on:
       - product-service
     image: codemotiontraining/api-gateway-zuul-proxy:latest
     ports:
       - "8080:8080"
     restart: always
     environment:
       PORT: 8080
       PRODUCT_SERVICE_URL: "http://localhost:8081"
     network_mode: "host"
      
   product-service:
     image: codemotiontraining/api-gateway-product-service:latest
     ports:
       - "8081:8081"
     restart: always
     environment:
       PORT: 8081
     network_mode: "host"