server:
  port: ${PORT:8081}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://127.0.0.1:8761/eureka/}
    healthcheck:
      enabled: true
    lease:
      duration: 5

spring:
  application:
    name: shop-service

logging:
  level:
    com.example.microservices: ${LOG_LEVEL:DEBUG}